# Generated by Django 5.2.4 on 2025-07-04 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_auditlog_options_inventory_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
